# Aggregations

In [1]:
# going from clean 2024 data 
import os 
os.getcwd()
os.chdir("/Users/ellawileman/Documents/last_sem/dsci_capstone/final_repo/US-Census-Voting-and-Registration-DSCI-Capstone-Project/clean_data")

'/Users/rmclatcher/Desktop/Capstone_Project/US-Census-Voting-and-Registration-DSCI-Capstone-Project'

In [1127]:
import pandas as pd
data = pd.read_csv("nov24pub_clean.csv") # replace with your own path to clean data on your machine

In [1128]:
data

,HRHHID,HRMONTH,HRYEAR4,HURESPLI,HUFINAL,FILLER,HETENURE,HEHOUSUT,HETELHHD,HETELAVL,...,PRSUPINT,PES1,PES2,PES3,PES4,PES5,PES6,PES7,PRS8,PESCK4
0,920760069071210,11,2024,2,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,1,6,4,2
1,920760069071210,11,2024,2,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,1,6,4,1
2,50057098511186,11,2024,1,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,1,9,4,1
3,6110057715727,11,2024,2,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,1,-2,4,1
4,6110057715727,11,2024,2,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,1,-2,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62404,740955848011240,11,2024,1,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,2,6,4,1
62405,740955848011240,11,2024,1,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,2,6,4,2
62406,651408019271540,11,2024,1,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,1,8,4,1
62407,75183059016886,11,2024,2,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,2,8,4,2
62408,75183059016886,11,2024,2,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,2,8,4,1

In [1129]:
data["PEHSPNON"]

0        2
1        2
2        2
3        2
4        2
        ..
62404    2
62405    2
62406    2
62407    2
62408    2
Name: PEHSPNON, Length: 62409, dtype: int64

In [1130]:
data.head()

,HRHHID,HRMONTH,HRYEAR4,HURESPLI,HUFINAL,FILLER,HETENURE,HEHOUSUT,HETELHHD,HETELAVL,...,PRSUPINT,PES1,PES2,PES3,PES4,PES5,PES6,PES7,PRS8,PESCK4
0,920760069071210,11,2024,2,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,1,6,4,2
1,920760069071210,11,2024,2,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,1,6,4,1
2,50057098511186,11,2024,1,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,1,9,4,1
3,6110057715727,11,2024,2,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,1,-2,4,1
4,6110057715727,11,2024,2,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,1,-2,4,1

In [1131]:
# identifier for state
data["GESTFIPS"].value_counts()

GESTFIPS
6     4953
48    3278
12    2564
36    2071
42    1918
17    1645
54    1556
39    1538
26    1447
37    1365
25    1308
16    1291
22    1280
30    1243
47    1227
51    1205
13    1203
1     1196
53    1175
34    1172
28    1164
5     1138
45    1068
41    1063
35    1054
40    1036
15    1035
49    1031
56    1022
55    1020
18    1019
11    1014
29    1007
38     996
50     964
27     921
33     861
19     845
4      840
20     833
32     831
31     817
46     754
21     737
24     733
8      728
10     726
9      710
2      680
23     569
44     558
Name: count, dtype: int64

In [1132]:
data = data.rename(columns={
    "PRTAGE": "age", 
    "PESEX": "sex", 
    "PEMARITL": "marital_status",
    "PEEDUCA": "education",
    "HEFAMINC": "family_income",
    "PRCHLD": "number_of_children",
    'PTDTRACE': 'race',
    'PEHSPNON': 'hispanic_flag',
    'PWSSWGT': 'weight',
    'PRS8': 'time_at_curr_address',
    'PRNLFSCH': 'curr_student', 
    'HETENURE': 'lease_type',
    'PRDTOCC1':"job_industry_code",
    "GEDIV":"geo_region",
    "PEDIPGED": "GED_or_HS",
    "PES1": "did_vote"
})

In [1133]:
data["did_vote"].value_counts()

did_vote
1    48387
2    14022
Name: count, dtype: int64

In [1134]:
data.loc[data['did_vote'] == 2, 'did_vote'] = 0

In [1135]:
# subset only a few features for now, can add more in later
data_subset = data[["age","sex", "marital_status","education","family_income","race","hispanic_flag","weight", "time_at_curr_address","curr_student","lease_type","job_industry_code","geo_region","GED_or_HS","did_vote"]]
data_subset

,age,sex,marital_status,education,family_income,race,hispanic_flag,weight,time_at_curr_address,curr_student,lease_type,job_industry_code,geo_region,GED_or_HS,did_vote
0,73,2,1,39,10,1,2,18354163,4,-1,1,-1,6,1,1
1,76,1,1,43,10,1,2,15592437,4,-1,1,-1,6,-1,1
2,85,2,3,39,15,1,2,16356249,4,-1,1,-1,6,1,1
3,67,1,1,40,16,1,2,20773863,4,-1,1,16,6,-1,1
4,66,2,1,40,16,1,2,16796510,4,-1,1,-1,6,-1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62404,69,1,1,40,16,1,2,7651462,4,-1,1,16,5,-1,1
62405,65,2,1,39,16,1,2,6827271,4,-1,1,-1,5,1,1
62406,66,1,1,41,12,1,2,3872403,4,-1,1,21,8,-1,1
62407,73,1,1,39,13,1,2,2790829,4,-1,1,-1,8,1,1
62408,70,2,1,39,13,1,2,2405480,4,-1,1,16,8,1,1

In [1136]:
# reducing cardinality of age feature by binning
bins = [18, 25, 35, 45, 55, 65, 100]
labels = ["18-24", "25-34", "35-44", "45-54", "55-64", "65+"]

data_subset["age_group"] = pd.cut(
    data_subset["age"],
    bins=bins,
    labels=labels,
    right=False
)

# drop original variable 
data_subset = data_subset.drop(columns=["age"])

/var/folders/yz/btvl331d4g54624wdzgx_2hc0000gn/T/ipykernel_21423/2859625887.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_subset["age_group"] = pd.cut(

In [1137]:
data_subset

,sex,marital_status,education,family_income,race,hispanic_flag,weight,time_at_curr_address,curr_student,lease_type,job_industry_code,geo_region,GED_or_HS,did_vote,age_group
0,2,1,39,10,1,2,18354163,4,-1,1,-1,6,1,1,65+
1,1,1,43,10,1,2,15592437,4,-1,1,-1,6,-1,1,65+
2,2,3,39,15,1,2,16356249,4,-1,1,-1,6,1,1,65+
3,1,1,40,16,1,2,20773863,4,-1,1,16,6,-1,1,65+
4,2,1,40,16,1,2,16796510,4,-1,1,-1,6,-1,1,65+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62404,1,1,40,16,1,2,7651462,4,-1,1,16,5,-1,1,65+
62405,2,1,39,16,1,2,6827271,4,-1,1,-1,5,1,1,65+
62406,1,1,41,12,1,2,3872403,4,-1,1,21,8,-1,1,65+
62407,1,1,39,13,1,2,2790829,4,-1,1,-1,8,1,1,65+
62408,2,1,39,13,1,2,2405480,4,-1,1,16,8,1,1,65+

In [1138]:
# JUST DOING A SMALL FEATURE SET FOR NOW 
# CAN INCLUDE MORE LATER (AND INCLUDE A FORMAL FEATURE SELECTION)


# note: need to decrease cardinality of columns we use so it doesnt explode to so many demographic proportion columns

# doing this on 2024, can apply to all other years as seperate time snapshots.

In [1139]:
data_subset.nunique()

sex                         2
marital_status              6
education                  16
family_income              16
race                       24
hispanic_flag               2
weight                  39354
time_at_curr_address        5
curr_student                3
lease_type                  3
job_industry_code          24
geo_region                  9
GED_or_HS                   3
did_vote                    2
age_group                   6
dtype: int64

In [1140]:
# reduce cardinality

In [1141]:
data_subset.columns

Index(['sex', 'marital_status', 'education', 'family_income', 'race',
       'hispanic_flag', 'weight', 'time_at_curr_address', 'curr_student',
       'lease_type', 'job_industry_code', 'geo_region', 'GED_or_HS',
       'did_vote', 'age_group'],
      dtype='object')

In [1142]:
data_subset['hispanic_flag'].mask(data_subset['hispanic_flag'] == 1, 'Hispanic', inplace=True)
data_subset['hispanic_flag'].mask(data_subset['hispanic_flag'] == 2, 'Non-Hispanic', inplace=True)

/var/folders/yz/btvl331d4g54624wdzgx_2hc0000gn/T/ipykernel_21423/130747232.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_subset['hispanic_flag'].mask(data_subset['hispanic_flag'] == 1, 'Hispanic', inplace=True)
/var/folders/yz/btvl331d4g54624wdzgx_2hc0000gn/T/ipykernel_21423/130747232.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Hispanic' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_subset['hispanic_flag'].mask(data_subset['hispanic_flag'] == 1, 'Hispanic', inplace=True)

In [1143]:
# group most common races 
data_subset.loc[data_subset['race'] == 1, 'race_grouped'] = 'white_only'
data_subset.loc[data_subset['race'] == 2, 'race_grouped'] = 'black_only'
data_subset.loc[data_subset['race'] == 3, 'race_grouped'] = 'american_indian_only'
data_subset.loc[data_subset['race'] == 4, 'race_grouped'] = 'asian_only'
data_subset.loc[data_subset['race'] == 5, 'race_grouped'] = 'PI_only'
data_subset.loc[(data_subset['race'] != 1) & (data_subset['race'] != 2) & (data_subset['race'] != 3) & (data_subset['race'] != 4) & (data_subset['race'] != 5), 'race_grouped'] = 'multiracial'

data_subset = data_subset.drop(columns="race")

In [1144]:
data_subset["family_income"].value_counts()

family_income
16    14271
15    11077
14     8611
13     6281
12     4489
11     4030
10     2495
9      2435
7      1956
8      1874
6      1290
1       987
4       975
5       859
2       404
3       375
Name: count, dtype: int64

In [1145]:
# Low class
# categories 1-6
# up to 20k
data_subset.loc[(data_subset['family_income'] == 1) | (data_subset['family_income'] == 2) | (data_subset['family_income'] == 3) | (data_subset['family_income'] == 4) | (data_subset['family_income'] == 5) | (data_subset['family_income'] == 6), 'family_income_grouped'] = 'low_income'

# Lower middle class
# categories 7-10
data_subset.loc[(data_subset['family_income'] == 7) | (data_subset['family_income'] == 8) | (data_subset['family_income'] == 9) | (data_subset['family_income'] == 10), 'family_income_grouped'] = 'lower_middle_class'


# True middle class
# categories 11-13
data_subset.loc[(data_subset['family_income'] == 11) | (data_subset['family_income'] == 12) | (data_subset['family_income'] == 13), 'family_income_grouped'] = 'middle_class'


# Upper middle class
# categories 14-15
data_subset.loc[(data_subset['family_income'] == 14) | (data_subset['family_income'] == 15), 'family_income_grouped'] = 'upper_middle_class'

# Upper class
# category 16
# note the cutoff is 150k in census data so we cannot differentiate further

data_subset.loc[data_subset['family_income'] == 16, 'family_income_grouped'] = 'high_income'

# drop original column
data_subset = data_subset.drop(columns="family_income")

In [1146]:
# reduce cardinality of number of children 

'''
# No children
data_subset.loc[data_subset['number_of_children'] == 0, 'children_grouped'] = 'No children'
# 1-2 children
data_subset.loc[(data_subset['number_of_children'] == 1) | (data_subset['number_of_children'] == 2), 'children_grouped'] = '1-2 children'

# 3+ children
data_subset.loc[data_subset['number_of_children'] > 2, 'children_grouped'] = '3+ children'

# drop original column and keep group
data_subset = data_subset.drop(columns="number_of_children")
'''

'\n# No children\ndata_subset.loc[data_subset[\'number_of_children\'] == 0, \'children_grouped\'] = \'No children\'\n# 1-2 children\ndata_subset.loc[(data_subset[\'number_of_children\'] == 1) | (data_subset[\'number_of_children\'] == 2), \'children_grouped\'] = \'1-2 children\'\n\n# 3+ children\ndata_subset.loc[data_subset[\'number_of_children\'] > 2, \'children_grouped\'] = \'3+ children\'\n\n# drop original column and keep group\ndata_subset = data_subset.drop(columns="number_of_children")\n'

In [1147]:
# reduce cardinality of education feature

# did not complete high school
data_subset.loc[(data_subset['education'] >= 31) & (data_subset['education'] <= 38), 'education_grouped'] = 'less_than_highschool'
data_subset.loc[data_subset['education'] == 39, 'education_grouped'] = 'high_school_GED_completed'
data_subset.loc[data_subset['education'] == 40, 'education_grouped'] = 'some_college'
data_subset.loc[(data_subset['education'] == 41) | (data_subset['education'] == 42), 'education_grouped'] = 'associates'
data_subset.loc[(data_subset['education'] == 43), 'education_grouped'] = 'bachelors'
data_subset.loc[(data_subset['education'] > 43), 'education_grouped'] = 'masters_and_above'

# drop original high-cardinality column
data_subset = data_subset.drop(columns="education")

In [1148]:
data_subset.nunique()

sex                          2
marital_status               6
hispanic_flag                2
weight                   39354
time_at_curr_address         5
curr_student                 3
lease_type                   3
job_industry_code           24
geo_region                   9
GED_or_HS                    3
did_vote                     2
age_group                    6
race_grouped                 6
family_income_grouped        5
education_grouped            6
dtype: int64

In [1149]:
# Choose the features we talked about on 4/16
data_subset = data_subset[["time_at_curr_address", "curr_student","lease_type","marital_status", "job_industry_code","GED_or_HS","sex","race_grouped","geo_region", "education_grouped", "age_group", "family_income_grouped", "weight","did_vote"]]

In [1150]:
year = 2024 # append and group by year so we can concatenate after performing this on all 

data_subset["year"] = year
# AGGREGATING BY DEMOGRAPHIC GROUP 
# encode the features we don't want to group by in the rows
grouped_cols = ["time_at_curr_address", "curr_student","lease_type","marital_status", "job_industry_code","GED_or_HS","sex","race_grouped","did_vote"]

dummies_df = pd.get_dummies(data_subset, columns=grouped_cols)

# convert the dummies into binary variables for grouping
# dummies_df = dummies_df.apply(lambda x: (x > 0).astype(int) if x.name.startswith(("marital_status", "hispanic_flag", "education_grouped","family_income_grouped", "children_grouped","veteran")) else x)

# multiply the weight column by the dummy variables to get the weighted count for each group
for col in dummies_df.columns:
    if col.startswith(tuple(grouped_cols)):
        dummies_df[col] = dummies_df[col] * dummies_df["weight"]



# for each group, the proportion of each category is the sum of the weighted counts for that category divided by the total weight for that group
grouped = dummies_df.groupby(["geo_region", "education_grouped", "age_group", "family_income_grouped"]).sum()

grouped.head(50)

feature_cols = [
    c for c in grouped.columns
    if any(c.startswith(p) for p in grouped_cols)
]
'''
grouped_nozeros = grouped[grouped["weight"] > 0] # drop rows with 0 weight
grouped_nozeros
'''

'''
feature_cols = [c for c in grouped.columns if c != "weight"]
grouped = grouped.copy()
grouped.loc[grouped["weight"] == 0, feature_cols] = 0

grouped[feature_cols] = grouped[feature_cols].div(grouped["weight"], axis=0)
'''

import numpy as np
denom = grouped["weight"].replace(0, np.nan)

grouped[feature_cols] = grouped[feature_cols].div(denom, axis=0)

# replace NaNs caused by 0-weight groups
grouped[feature_cols] = grouped[feature_cols].fillna(0)

# drop did_vote_0 column
grouped = grouped.drop(columns="did_vote_0")

grouped.head(50)


# we dropped the zero weight rows so this may vary from year to year

/var/folders/yz/btvl331d4g54624wdzgx_2hc0000gn/T/ipykernel_21423/3272630399.py:21: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = dummies_df.groupby(["geo_region", "education_grouped", "age_group", "family_income_grouped"]).sum()

                                                                  weight  \
geo_region education_grouped age_group family_income_grouped
1          associates        18-24     high_income             174758826
                                       low_income                      0
                                       lower_middle_class       19938496
                                       middle_class             25079642
                                       upper_middle_class       88875211
                             25-34     high_income             173173530
                                       low_income               32206212
                                       lower_middle_class      121473246
                                       middle_class            240686910
                                       upper_middle_class      548297643
                             35-44     high_income             323994324
                                       low_income                      0
                                       lower_middle_class      135274925
                                       middle_class            169171091
                                       upper_middle_class      620955900
                             45-54     high_income             502696616
                                       low_income               73039128
                                       lower_middle_class      169267469
                                       middle_class            187558269
                                       upper_middle_class      547418572
                             55-64     high_income             527453294
                                       low_income               49217674
                                       lower_middle_class      164911175
                                       middle_class            359375610
                                       upper_middle_class      966044150
                             65+       high_income             371843031
                                       low_income              174870494
                                       lower_middle_class      375228640
                                       middle_class            804405523
                                       upper_middle_class      520849098
           bachelors         18-24     high_income             772703575
                                       low_income              203894856
                                       lower_middle_class      121432134
                                       middle_class            211256303
                                       upper_middle_class      752281939
                             25-34     high_income            2014930678
                                       low_income               99938146
                                       lower_middle_class      339117625
                                       middle_class            694779206
                                       upper_middle_class     1981242975
                             35-44     high_income            1902289288
                                       low_income               66292739
                                       lower_middle_class      136155894
                                       middle_class            352006733
                                       upper_middle_class     1844188219
                             45-54     high_income            2023959810
                                       low_income               10500597
                                       lower_middle_class      170177270
                                       middle_class            272751771
                                       upper_middle_class     1214354324

                                                                year  \
geo_region education_grouped age_group family_income_grouped
1          associates        18-24     high_income             12144
                                       low_income                  0
                                       lower_middle_class       4048
                                       middle_class             4048
                                       upper_middle_class       8096
                             25-34     high_income             14168
                                       low_income               4048
                                       lower_middle_class      12144
                                       middle_class            22264
                                       upper_middle_class      48576
                             35-44     high_income             36432
                                       low_income                  0
                                       lower_middle_class      10120
                                       middle_class            20240
                                       upper_middle_class      64768
                             45-54     high_income             44528
                                       low_income              12144
                                       lower_middle_class      22264
                                       middle_class            26312
                                       upper_middle_class      60720
                             55-64     high_income             56672
                                       low_income               8096
                                       lower_middle_class      20240
                                       middle_class            44528
                                       upper_middle_class     101200
                             65+       high_income             42504
                                       low_income              22264
                                       lower_middle_class      52624
                                       middle_class           103224
                                       upper_middle_class      70840
           bachelors         18-24     high_income             58696
                                       low_income              12144
                                       lower_middle_class       8096
                                       middle_class            14168
                                       upper_middle_class      66792
                             25-34     high_income            174064
                                       low_income              10120
                                       lower_middle_class      38456
                                       middle_class            62744
                                       upper_middle_class     204424
                             35-44     high_income            178112
                                       low_income               8096
                                       lower_middle_class      18216
                                       middle_class            42504
                                       upper_middle_class     224664
                             45-54     high_income            186208
                                       low_income               2024
                                       lower_middle_class      20240
                                       middle_class            36432
                                       upper_middle_class     139656

                                                              time_at_curr_address_-1  \
geo_region education_grouped age_group family_income_grouped
1          associates        18-24     high_income                           0.000000
                                       low_income                            0.000000
                                       lower_middle_class                    0.000000
                                       middle_class                          0.000000
                                       upper_middle_class                    0.000000
                             25-34     high_income                           0.145301
                                       low_income                            0.000000
                                       lower_middle_class                    0.000000
                                       middle_class                          0.000000
                                       upper_middle_class                    0.000000
                             35-44     high_income                           0.000000
                                       low_income                            0.000000
                                       lower_middle_class                    0.000000
                                       middle_class                          0.000000
                                       upper_middle_class                    0.108283
                             45-54     high_income                           0.069850
                                       low_income                            0.000000
                                       lower_middle_class                    0.000000
                                       middle_class                          0.000000
                                       upper_middle_class                    0.000000
                             55-64     high_income                           0.000000
                                       low_income                            0.000000
                                       lower_middle_class                    0.000000
                                       middle_class                          0.000000
                                       upper_middle_class                    0.000000
                             65+       high_income                           0.000000
                                       low_income                            0.000000
                                       lower_middle_class                    0.000000
                                       middle_class                          0.000000
                                       upper_middle_class                    0.000000
           bachelors         18-24     high_income                           0.000000
                                       low_income                            0.169696
                                       lower_middle_class                    0.000000
                                       middle_class                          0.000000
                                       upper_middle_class                    0.000000
                             25-34     high_income                           0.000000
                                       low_income                            0.000000
                                       lower_middle_class                    0.000000
                                       middle_class                          0.000000
                                       upper_middle_class                    0.000000
                             35-44     high_income                           0.000000
                                       low_income                            0.000000
                                       lower_middle_class                    0.000000
                                       middle_class                          0.015440
                                       upper_middle_class                    0.024486
                             45-54     high_income                           0.014191
                                       low_income                            0.000000
                                       lower_middle_class                    0.000000
                                       middle_class                          0.099488
                                       upper_middle_class                    0.003627

                                                              time_at_curr_address_1  \
geo_region education_grouped age_group family_income_grouped
1          associates        18-24     high_income                          0.000000
                                       low_income                           0.000000
                                       lower_middle_class                   0.000000
                                       middle_class                         0.000000
                                       upper_middle_class                   0.389311
                             25-34     high_income                          0.000000
                                       low_income                           0.851544
                                       lower_middle_class                   0.086267
                                       middle_class                         0.048591
                                       upper_middle_class                   0.046767
                             35-44     high_income                          0.086299
                                       low_income                           0.000000
                                       lower_middle_class                   0.000000
                                       middle_class                         0.000000
                                       upper_middle_class                   0.110360
                             45-54     high_income                          0.059224
                                       low_income                           0.526692
                                       lower_middle_class                   0.000000
                                       middle_class                         0.000000
                                       upper_middle_class                   0.000000
                             55-64     high_income                          0.000000
                                       low_income                           0.000000
                                       lower_middle_class                   0.106855
                                       middle_class                         0.000000
                                       upper_middle_class                   0.000000
                             65+       high_income                          0.000000
                                       low_income                           0.000000
                                       lower_middle_class                   0.017146
                                       middle_class                         0.015074
                                       upper_middle_class                   0.000000
           bachelors         18-24     high_income                          0.209029
                                       low_income                           0.655876
                                       lower_middle_class                   0.952909
                                       middle_class                         0.260568
                                       upper_middle_class                   0.388497
                             25-34     high_income                          0.150707
                                       low_income                           0.194399
                                       lower_middle_class                   0.262244
                                       middle_class                         0.189386
                                       upper_middle_class                   0.363063
                             35-44     high_income                          0.148387
                                       low_income                           0.000000
                                       lower_middle_class                   0.000000
                                       middle_class                         0.000000
                                       upper_middle_class                   0.060445
                             45-54     high_income                          0.036132
                                       low_income                           0.000000
                                       lower_middle_class                   0.021464
                                       middle_class                         0.000000
                                       upper_middle_class                   0.023458

                                                              time_at_curr_address_2  \
geo_region education_grouped age_group family_income_grouped
1          associates        18-24     high_income                          0.229121
                                       low_income                           0.000000
                                       lower_middle_class                   0.000000
                                       middle_class                         0.000000
                                       upper_middle_class                   0.000000
                             25-34     high_income                          0.000000
                                       low_income                           0.000000
                                       lower_middle_class                   0.000000
                                       middle_class                         0.292256
                                       upper_middle_class                   0.059623
                             35-44     high_income                          0.015744
                                       low_income                           0.000000
                                       lower_middle_class                   0.186902
                                       middle_class                         0.432149
                                       upper_middle_class                   0.065406
                             45-54     high_income                          0.064035
                                       low_income                           0.182588
                                       lower_middle_class                   0.151771
                                       middle_class                         0.024368
                                       upper_middle_class                   0.000000
                             55-64     high_income                          0.018584
                                       low_income                           0.245741
                                       lower_middle_class                   0.068751
                                       middle_class                         0.000000
                                       upper_middle_class                   0.000000
                             65+       high_income                          0.119765
                                       low_income                           0.152992
                                       lower_middle_class                   0.115697
                                       middle_class                         0.086545
                                       upper_middle_class                   0.000000
           bachelors         18-24     high_income                          0.040002
                                       low_income                           0.174428
                                       lower_middle_class                   0.000000
                                       middle_class                         0.483493
                                       upper_middle_class                   0.209274
                             25-34     high_income                          0.177080
                                       low_income                           0.000000
                                       lower_middle_class                   0.238746
                                       middle_class                         0.297347
                                       upper_middle_class                   0.178949
                             35-44     high_income                          0.113037
                                       low_income                           0.000000

In [1151]:
grouped.shape

(1620, 55)

In [1152]:
grouped.columns

Index(['weight', 'year', 'time_at_curr_address_-1', 'time_at_curr_address_1',
       'time_at_curr_address_2', 'time_at_curr_address_3',
       'time_at_curr_address_4', 'curr_student_-1', 'curr_student_1',
       'curr_student_2', 'lease_type_1', 'lease_type_2', 'lease_type_3',
       'marital_status_1', 'marital_status_2', 'marital_status_3',
       'marital_status_4', 'marital_status_5', 'marital_status_6',
       'job_industry_code_-1', 'job_industry_code_1', 'job_industry_code_2',
       'job_industry_code_3', 'job_industry_code_4', 'job_industry_code_5',
       'job_industry_code_6', 'job_industry_code_7', 'job_industry_code_8',
       'job_industry_code_9', 'job_industry_code_10', 'job_industry_code_11',
       'job_industry_code_12', 'job_industry_code_13', 'job_industry_code_14',
       'job_industry_code_15', 'job_industry_code_16', 'job_industry_code_17',
       'job_industry_code_18', 'job_industry_code_19', 'job_industry_code_20',
       'job_industry_code_21', 'job_industry_code_22', 'job_industry_code_23',
       'GED_or_HS_-1', 'GED_or_HS_1', 'GED_or_HS_2', 'sex_1', 'sex_2',
       'race_grouped_PI_only', 'race_grouped_american_indian_only',
       'race_grouped_asian_only', 'race_grouped_black_only',
       'race_grouped_multiracial', 'race_grouped_white_only', 'did_vote_1'],
      dtype='object')

In [1153]:
# Let's not do this for now

# May violate some time series assumptions 
grouped_nozeros = grouped[grouped["weight"] > 0] # drop rows with 0 weight
grouped_nozeros

feature_cols = [c for c in grouped_nozeros.columns if c != "weight"]

grouped_nozeros[feature_cols] = grouped_nozeros[feature_cols].div(grouped_nozeros["weight"], axis=0)

grouped_nozeros.head(50)

# 200 rows x 20 years ~ 4000 rows 

# we dropped the zero weight rows so this may vary from year to year

/var/folders/yz/btvl331d4g54624wdzgx_2hc0000gn/T/ipykernel_21423/2262534474.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_nozeros[feature_cols] = grouped_nozeros[feature_cols].div(grouped_nozeros["weight"], axis=0)

                                                                  weight  \
geo_region education_grouped age_group family_income_grouped
1          associates        18-24     high_income             174758826
                                       lower_middle_class       19938496
                                       middle_class             25079642
                                       upper_middle_class       88875211
                             25-34     high_income             173173530
                                       low_income               32206212
                                       lower_middle_class      121473246
                                       middle_class            240686910
                                       upper_middle_class      548297643
                             35-44     high_income             323994324
                                       lower_middle_class      135274925
                                       middle_class            169171091
                                       upper_middle_class      620955900
                             45-54     high_income             502696616
                                       low_income               73039128
                                       lower_middle_class      169267469
                                       middle_class            187558269
                                       upper_middle_class      547418572
                             55-64     high_income             527453294
                                       low_income               49217674
                                       lower_middle_class      164911175
                                       middle_class            359375610
                                       upper_middle_class      966044150
                             65+       high_income             371843031
                                       low_income              174870494
                                       lower_middle_class      375228640
                                       middle_class            804405523
                                       upper_middle_class      520849098
           bachelors         18-24     high_income             772703575
                                       low_income              203894856
                                       lower_middle_class      121432134
                                       middle_class            211256303
                                       upper_middle_class      752281939
                             25-34     high_income            2014930678
                                       low_income               99938146
                                       lower_middle_class      339117625
                                       middle_class            694779206
                                       upper_middle_class     1981242975
                             35-44     high_income            1902289288
                                       low_income               66292739
                                       lower_middle_class      136155894
                                       middle_class            352006733
                                       upper_middle_class     1844188219
                             45-54     high_income            2023959810
                                       low_income               10500597
                                       lower_middle_class      170177270
                                       middle_class            272751771
                                       upper_middle_class     1214354324
                             55-64     high_income            1641442540
                                       low_income              108181188

                                                                  year  \
geo_region education_grouped age_group family_income_grouped
1          associates        18-24     high_income            0.000069
                                       lower_middle_class     0.000203
                                       middle_class           0.000161
                                       upper_middle_class     0.000091
                             25-34     high_income            0.000082
                                       low_income             0.000126
                                       lower_middle_class     0.000100
                                       middle_class           0.000093
                                       upper_middle_class     0.000089
                             35-44     high_income            0.000112
                                       lower_middle_class     0.000075
                                       middle_class           0.000120
                                       upper_middle_class     0.000104
                             45-54     high_income            0.000089
                                       low_income             0.000166
                                       lower_middle_class     0.000132
                                       middle_class           0.000140
                                       upper_middle_class     0.000111
                             55-64     high_income            0.000107
                                       low_income             0.000164
                                       lower_middle_class     0.000123
                                       middle_class           0.000124
                                       upper_middle_class     0.000105
                             65+       high_income            0.000114
                                       low_income             0.000127
                                       lower_middle_class     0.000140
                                       middle_class           0.000128
                                       upper_middle_class     0.000136
           bachelors         18-24     high_income            0.000076
                                       low_income             0.000060
                                       lower_middle_class     0.000067
                                       middle_class           0.000067
                                       upper_middle_class     0.000089
                             25-34     high_income            0.000086
                                       low_income             0.000101
                                       lower_middle_class     0.000113
                                       middle_class           0.000090
                                       upper_middle_class     0.000103
                             35-44     high_income            0.000094
                                       low_income             0.000122
                                       lower_middle_class     0.000134
                                       middle_class           0.000121
                                       upper_middle_class     0.000122
                             45-54     high_income            0.000092
                                       low_income             0.000193
                                       lower_middle_class     0.000119
                                       middle_class           0.000134
                                       upper_middle_class     0.000115
                             55-64     high_income            0.000113
                                       low_income             0.000112

                                                              time_at_curr_address_-1  \
geo_region education_grouped age_group family_income_grouped
1          associates        18-24     high_income                       0.000000e+00
                                       lower_middle_class                0.000000e+00
                                       middle_class                      0.000000e+00
                                       upper_middle_class                0.000000e+00
                             25-34     high_income                       8.390475e-10
                                       low_income                        0.000000e+00
                                       lower_middle_class                0.000000e+00
                                       middle_class                      0.000000e+00
                                       upper_middle_class                0.000000e+00
                             35-44     high_income                       0.000000e+00
                                       lower_middle_class                0.000000e+00
                                       middle_class                      0.000000e+00
                                       upper_middle_class                1.743816e-10
                             45-54     high_income                       1.389512e-10
                                       low_income                        0.000000e+00
                                       lower_middle_class                0.000000e+00
                                       middle_class                      0.000000e+00
                                       upper_middle_class                0.000000e+00
                             55-64     high_income                       0.000000e+00
                                       low_income                        0.000000e+00
                                       lower_middle_class                0.000000e+00
                                       middle_class                      0.000000e+00
                                       upper_middle_class                0.000000e+00
                             65+       high_income                       0.000000e+00
                                       low_income                        0.000000e+00
                                       lower_middle_class                0.000000e+00
                                       middle_class                      0.000000e+00
                                       upper_middle_class                0.000000e+00
           bachelors         18-24     high_income                       0.000000e+00
                                       low_income                        8.322716e-10
                                       lower_middle_class                0.000000e+00
                                       middle_class                      0.000000e+00
                                       upper_middle_class                0.000000e+00
                             25-34     high_income                       0.000000e+00
                                       low_income                        0.000000e+00
                                       lower_middle_class                0.000000e+00
                                       middle_class                      0.000000e+00
                                       upper_middle_class                0.000000e+00
                             35-44     high_income                       0.000000e+00
                                       low_income                        0.000000e+00
                                       lower_middle_class                0.000000e+00
                                       middle_class                      4.386335e-11
                                       upper_middle_class                1.327766e-11
                             45-54     high_income                       7.011353e-12
                                       low_income                        0.000000e+00
                                       lower_middle_class                0.000000e+00
                                       middle_class                      3.647579e-10
                                       upper_middle_class                2.986856e-12
                             55-64     high_income                       3.512512e-12
                                       low_income                        0.000000e+00

                                                              time_at_curr_address_1  \
geo_region education_grouped age_group family_income_grouped
1          associates        18-24     high_income                      0.000000e+00
                                       lower_middle_class               0.000000e+00
                                       middle_class                     0.000000e+00
                                       upper_middle_class               4.380426e-09
                             25-34     high_income                      0.000000e+00
                                       low_income                       2.644036e-08
                                       lower_middle_class               7.101699e-10
                                       middle_class                     2.018843e-10
                                       upper_middle_class               8.529459e-11
                             35-44     high_income                      2.663597e-10
                                       lower_middle_class               0.000000e+00
                                       middle_class                     0.000000e+00
                                       upper_middle_class               1.777260e-10
                             45-54     high_income                      1.178130e-10
                                       low_income                       7.211094e-09
                                       lower_middle_class               0.000000e+00
                                       middle_class                     0.000000e+00
                                       upper_middle_class               0.000000e+00
                             55-64     high_income                      0.000000e+00
                                       low_income                       0.000000e+00
                                       lower_middle_class               6.479567e-10
                                       middle_class                     0.000000e+00
                                       upper_middle_class               0.000000e+00
                             65+       high_income                      0.000000e+00
                                       low_income                       0.000000e+00
                                       lower_middle_class               4.569440e-11
                                       middle_class                     1.873898e-11
                                       upper_middle_class               0.000000e+00
           bachelors         18-24     high_income                      2.705162e-10
                                       low_income                       3.216737e-09
                                       lower_middle_class               7.847254e-09
                                       middle_class                     1.233419e-09
                                       upper_middle_class               5.164243e-10
                             25-34     high_income                      7.479523e-11
                                       low_income                       1.945195e-09
                                       lower_middle_class               7.733122e-10
                                       middle_class                     2.725848e-10
                                       upper_middle_class               1.832503e-10
                             35-44     high_income                      7.800424e-11
                                       low_income                       0.000000e+00
                                       lower_middle_class               0.000000e+00
                                       middle_class                     0.000000e+00
                                       upper_middle_class               3.277595e-11
                             45-54     high_income                      1.785211e-11
                                       low_income                       0.000000e+00
                                       lower_middle_class               1.261278e-10
                                       middle_class                     0.000000e+00
                                       upper_middle_class               1.931691e-11
                             55-64     high_income                      4.715344e-11
                                       low_income                       2.414613e-09

                                                              time_at_curr_address_2  \
geo_region education_grouped age_group family_income_grouped
1          associates        18-24     high_income                      1.311070e-09
                                       lower_middle_class               0.000000e+00
                                       middle_class                     0.000000e+00
                                       upper_middle_class               0.000000e+00
                             25-34     high_income                      0.000000e+00
                                       low_income                       0.000000e+00
                                       lower_middle_class               0.000000e+00
                                       middle_class                     1.214258e-09
                                       upper_middle_class               1.087424e-10
                             35-44     high_income                      4.859372e-11
                                       lower_middle_class               1.381643e-09
                                       middle_class                     2.554506e-09
                                       upper_middle_class               1.053304e-10
                             45-54     high_income                      1.273838e-10
                                       low_income                       2.499864e-09
                                       lower_middle_class               8.966367e-10
                                       middle_class                     1.299209e-10
                                       upper_middle_class               0.000000e+00
                             55-64     high_income                      3.523429e-11
                                       low_income                       4.992946e-09
                                       lower_middle_class               4.168959e-10
                                       middle_class                     0.000000e+00
                                       upper_middle_class               0.000000e+00
                             65+       high_income                      3.220855e-10
                                       low_income                       8.748901e-10
                                       lower_middle_class               3.083382e-10
                                       middle_class                     1.075893e-10
                                       upper_middle_class               0.000000e+00
           bachelors         18-24     high_income                      5.176921e-11
                                       low_income                       8.554803e-10
                                       lower_middle_class               0.000000e+00
                                       middle_class                     2.288658e-09
                                       upper_middle_class               2.781856e-10
                             25-34     high_income                      8.788404e-11
                                       low_income                       0.000000e+00
                                       lower_middle_class               7.040217e-10
                                       middle_class                     4.279730e-10
                                       upper_middle_class               9.032165e-11
                             35-44     high_income                      5.942171e-11
                                       low_income                       0.000000e+00
                                       lower_middle_class               2.051105e-09