# Aggregations

In [408]:
# going from clean 2024 data 
import os 
os.getcwd()
os.chdir("/Users/ellawileman/Documents/last_sem/dsci_capstone/final_repo/US-Census-Voting-and-Registration-DSCI-Capstone-Project/clean_data")

In [409]:
import pandas as pd
data = pd.read_csv("nov24pub_clean.csv") # replace with your own path to clean data on your machine

In [ ]:
data

In [410]:
data["PEHSPNON"]

0        2
1        2
2        2
3        2
4        2
        ..
62404    2
62405    2
62406    2
62407    2
62408    2
Name: PEHSPNON, Length: 62409, dtype: int64

In [411]:
data.head()

,HRHHID,HRMONTH,HRYEAR4,HURESPLI,HUFINAL,FILLER,HETENURE,HEHOUSUT,HETELHHD,HETELAVL,...,PRSUPINT,PES1,PES2,PES3,PES4,PES5,PES6,PES7,PRS8,PESCK4
0,920760069071210,11,2024,2,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,1,6,4,2
1,920760069071210,11,2024,2,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,1,6,4,1
2,50057098511186,11,2024,1,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,1,9,4,1
3,6110057715727,11,2024,2,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,1,-2,4,1
4,6110057715727,11,2024,2,201,NaN,1,1,1,-1,...,1,1,1,-1,-1,1,1,-2,4,1

In [412]:
# identifier for state
data["GESTFIPS"].value_counts()

GESTFIPS
6     4953
48    3278
12    2564
36    2071
42    1918
17    1645
54    1556
39    1538
26    1447
37    1365
25    1308
16    1291
22    1280
30    1243
47    1227
51    1205
13    1203
1     1196
53    1175
34    1172
28    1164
5     1138
45    1068
41    1063
35    1054
40    1036
15    1035
49    1031
56    1022
55    1020
18    1019
11    1014
29    1007
38     996
50     964
27     921
33     861
19     845
4      840
20     833
32     831
31     817
46     754
21     737
24     733
8      728
10     726
9      710
2      680
23     569
44     558
Name: count, dtype: int64

In [413]:
data = data.rename(columns={
    "PRTAGE": "age",
    "PESEX": "sex",
    "PEMARITL": "marital_status",
    "PEEDUCA": "education",
    "HEFAMINC": "family_income",
    "PRCHLD": "number_of_children",
    'PTDTRACE': 'race',
    'PEHSPNON': 'hispanic_flag',
    'PEAFEVER': 'veteran',
    'PWSSWGT': 'weight',
    'GESTFIPS': 'state'

})

In [414]:
# subset only a few features for now, can add more in later
data_subset = data[["age","sex", "marital_status","education","family_income","number_of_children","race","hispanic_flag", "veteran",'state',"weight"]]
data_subset

,age,sex,marital_status,education,family_income,number_of_children,race,hispanic_flag,veteran,state,weight
0,73,2,1,39,10,0,1,2,2,1,18354163
1,76,1,1,43,10,0,1,2,1,1,15592437
2,85,2,3,39,15,0,1,2,2,1,16356249
3,67,1,1,40,16,0,1,2,2,1,20773863
4,66,2,1,40,16,0,1,2,2,1,16796510
...,...,...,...,...,...,...,...,...,...,...,...
62404,69,1,1,40,16,0,1,2,2,54,7651462
62405,65,2,1,39,16,0,1,2,2,54,6827271
62406,66,1,1,41,12,0,1,2,2,56,3872403
62407,73,1,1,39,13,0,1,2,2,56,2790829
62408,70,2,1,39,13,0,1,2,2,56,2405480

In [415]:
# reducing cardinality of age feature by binning
bins = [18, 25, 35, 45, 55, 65, 100]
labels = ["18-24", "25-34", "35-44", "45-54", "55-64", "65+"]

data_subset["age_group"] = pd.cut(
    data_subset["age"],
    bins=bins,
    labels=labels,
    right=False
)

# drop original variable 
data_subset = data_subset.drop(columns=["age"])

/var/folders/yz/btvl331d4g54624wdzgx_2hc0000gn/T/ipykernel_21423/2859625887.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_subset["age_group"] = pd.cut(

In [416]:
data_subset

,sex,marital_status,education,family_income,number_of_children,race,hispanic_flag,veteran,state,weight,age_group
0,2,1,39,10,0,1,2,2,1,18354163,65+
1,1,1,43,10,0,1,2,1,1,15592437,65+
2,2,3,39,15,0,1,2,2,1,16356249,65+
3,1,1,40,16,0,1,2,2,1,20773863,65+
4,2,1,40,16,0,1,2,2,1,16796510,65+
...,...,...,...,...,...,...,...,...,...,...,...
62404,1,1,40,16,0,1,2,2,54,7651462,65+
62405,2,1,39,16,0,1,2,2,54,6827271,65+
62406,1,1,41,12,0,1,2,2,56,3872403,65+
62407,1,1,39,13,0,1,2,2,56,2790829,65+
62408,2,1,39,13,0,1,2,2,56,2405480,65+

In [417]:
# JUST DOING A SMALL FEATURE SET FOR NOW 
# CAN INCLUDE MORE LATER (AND INCLUDE A FORMAL FEATURE SELECTION)


# note: need to decrease cardinality of columns we use so it doesnt explode to so many demographic proportion columns

# doing this on 2024, can apply to all other years as seperate time snapshots.

In [418]:
data_subset.nunique()

sex                       2
marital_status            6
education                16
family_income            16
number_of_children       16
race                     24
hispanic_flag             2
veteran                   2
state                    51
weight                39354
age_group                 6
dtype: int64

In [419]:
# reduce cardinality

In [420]:
data_subset.columns

Index(['sex', 'marital_status', 'education', 'family_income',
       'number_of_children', 'race', 'hispanic_flag', 'veteran', 'state',
       'weight', 'age_group'],
      dtype='object')

In [421]:
data_subset['hispanic_flag'].mask(data_subset['hispanic_flag'] == 1, 'Hispanic', inplace=True)
data_subset['hispanic_flag'].mask(data_subset['hispanic_flag'] == 2, 'Non-Hispanic', inplace=True)

/var/folders/yz/btvl331d4g54624wdzgx_2hc0000gn/T/ipykernel_21423/130747232.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_subset['hispanic_flag'].mask(data_subset['hispanic_flag'] == 1, 'Hispanic', inplace=True)
/var/folders/yz/btvl331d4g54624wdzgx_2hc0000gn/T/ipykernel_21423/130747232.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Hispanic' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_subset['hispanic_flag'].mask(data_subset['hispanic_flag'] == 1, 'Hispanic', inplace=True)

In [422]:
# group most common races 
data_subset.loc[data_subset['race'] == 1, 'race_grouped'] = 'white_only'
data_subset.loc[data_subset['race'] == 2, 'race_grouped'] = 'black_only'
data_subset.loc[data_subset['race'] == 3, 'race_grouped'] = 'american_indian_only'
data_subset.loc[data_subset['race'] == 4, 'race_grouped'] = 'asian_only'
data_subset.loc[data_subset['race'] == 5, 'race_grouped'] = 'white_only'
data_subset.loc[(data_subset['race'] != 1) & (data_subset['race'] != 2) & (data_subset['race'] != 3) & (data_subset['race'] != 4) & (data_subset['race'] != 5), 'race_grouped'] = 'multiracial'

data_subset = data_subset.drop(columns="race")

In [423]:
data_subset["family_income"].value_counts()

family_income
16    14271
15    11077
14     8611
13     6281
12     4489
11     4030
10     2495
9      2435
7      1956
8      1874
6      1290
1       987
4       975
5       859
2       404
3       375
Name: count, dtype: int64

In [424]:
# Low class
# categories 1-6
# up to 20k
data_subset.loc[(data_subset['family_income'] == 1) | (data_subset['family_income'] == 2) | (data_subset['family_income'] == 3) | (data_subset['family_income'] == 4) | (data_subset['family_income'] == 5) | (data_subset['family_income'] == 6), 'family_income_grouped'] = 'low_income'

# Lower middle class
# categories 7-10
data_subset.loc[(data_subset['family_income'] == 7) | (data_subset['family_income'] == 8) | (data_subset['family_income'] == 9) | (data_subset['family_income'] == 10), 'family_income_grouped'] = 'lower_middle_class'


# True middle class
# categories 11-13
data_subset.loc[(data_subset['family_income'] == 11) | (data_subset['family_income'] == 12) | (data_subset['family_income'] == 13), 'family_income_grouped'] = 'middle_class'


# Upper middle class
# categories 14-15
data_subset.loc[(data_subset['family_income'] == 14) | (data_subset['family_income'] == 15), 'family_income_grouped'] = 'upper_middle_class'

# Upper class
# category 16
# note the cutoff is 150k in census data so we cannot differentiate further

data_subset.loc[data_subset['family_income'] == 16, 'family_income_grouped'] = 'high_income'

# drop original column
data_subset = data_subset.drop(columns="family_income")

In [425]:
data_subset["number_of_children"].value_counts()

number_of_children
0     48677
3      3689
4      2578
10     1814
1      1416
8      1223
2       868
5       803
6       478
11      356
14      184
9        93
13       75
7        66
15       54
12       35
Name: count, dtype: int64

In [426]:
# reduce cardinality of number of children 

# No children
data_subset.loc[data_subset['number_of_children'] == 0, 'children_grouped'] = 'No children'
# 1-2 children
data_subset.loc[(data_subset['number_of_children'] == 1) | (data_subset['number_of_children'] == 2), 'children_grouped'] = '1-2 children'

# 3+ children
data_subset.loc[data_subset['number_of_children'] > 2, 'children_grouped'] = '3+ children'

# drop original column and keep group
data_subset = data_subset.drop(columns="number_of_children")

In [427]:
# reduce cardinality of education feature

# did not complete high school
data_subset.loc[(data_subset['education'] >= 31) & (data_subset['education'] <= 38), 'education_grouped'] = 'less_than_highschool'
data_subset.loc[(data_subset['education'] == 39) | (data_subset['education'] == 40), 'education_grouped'] = 'high_school_completed'
data_subset.loc[(data_subset['education'] == 41) | (data_subset['education'] == 42), 'education_grouped'] = 'associates'
data_subset.loc[(data_subset['education'] == 43), 'education_grouped'] = 'bachelors'
data_subset.loc[(data_subset['education'] > 43), 'education_grouped'] = 'masters_and_above'

# drop original high-cardinality column
data_subset = data_subset.drop(columns="education")

In [428]:
data_subset.nunique()

sex                          2
marital_status               6
hispanic_flag                2
veteran                      2
state                       51
weight                   39354
age_group                    6
race_grouped                 5
family_income_grouped        5
children_grouped             3
education_grouped            5
dtype: int64

In [ ]:
year = 2024 # append and group by year so we can concatenate after performing this on all 

# AGGREGATING BY DEMOGRAPHIC GROUP 
# encode the features we don't want to group by in the rows
grouped_cols = ["marital_status", "hispanic_flag", "education_grouped","family_income_grouped", "children_grouped","veteran"]

dummies_df = pd.get_dummies(data_subset, columns=grouped_cols)

# convert the dummies into binary variables for grouping
# dummies_df = dummies_df.apply(lambda x: (x > 0).astype(int) if x.name.startswith(("marital_status", "hispanic_flag", "education_grouped","family_income_grouped", "children_grouped","veteran")) else x)

# multiply the weight column by the dummy variables to get the weighted count for each group
for col in dummies_df.columns:
    if col.startswith(tuple(grouped_cols)):
        dummies_df[col] = dummies_df[col] * dummies_df["weight"]



# for each group, the proportion of each category is the sum of the weighted counts for that category divided by the total weight for that group
grouped = dummies_df.groupby(["state", "age_group", "sex", "race_grouped"]).sum()

grouped.head(50)

feature_cols = [
    c for c in grouped.columns
    if any(c.startswith(p) for p in grouped_cols)
]
'''
grouped_nozeros = grouped[grouped["weight"] > 0] # drop rows with 0 weight
grouped_nozeros
'''

'''
feature_cols = [c for c in grouped.columns if c != "weight"]
grouped = grouped.copy()
grouped.loc[grouped["weight"] == 0, feature_cols] = 0

grouped[feature_cols] = grouped[feature_cols].div(grouped["weight"], axis=0)
'''

import numpy as np
denom = grouped["weight"].replace(0, np.nan)

grouped[feature_cols] = grouped[feature_cols].div(denom, axis=0)

# replace NaNs caused by 0-weight groups
grouped[feature_cols] = grouped[feature_cols].fillna(0)
grouped.head(50)


# we dropped the zero weight rows so this may vary from year to year

/var/folders/yz/btvl331d4g54624wdzgx_2hc0000gn/T/ipykernel_21423/2690986964.py:18: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = dummies_df.groupby(["state", "age_group", "sex", "race_grouped"]).sum()

                                              weight  marital_status_1  \
state age_group sex race_grouped
1     18-24     1   american_indian_only           0          0.000000
                    asian_only                     0          0.000000
                    black_only             338638266          0.000000
                    multiracial                    0          0.000000
                    white_only            1228359227          0.089876
                2   american_indian_only           0          0.000000
                    asian_only              25780867          0.000000
                    black_only             321128931          0.000000
                    multiracial             29127629          0.000000
                    white_only             962224315          0.133826
      25-34     1   american_indian_only    38573846          1.000000
                    asian_only              47942734          1.000000
                    black_only             734906886          0.234602
                    multiracial                    0          0.000000
                    white_only            1619786948          0.500748
                2   american_indian_only    48199208          1.000000
                    asian_only              72297085          1.000000
                    black_only             968682631          0.094211
                    multiracial             36235191          1.000000
                    white_only            1556242328          0.658222
      35-44     1   american_indian_only           0          0.000000
                    asian_only              25738916          1.000000
                    black_only             509334030          0.326017
                    multiracial                    0          0.000000
                    white_only            1576168845          0.737124
                2   american_indian_only           0          0.000000
                    asian_only              48131421          1.000000
                    black_only             657558482          0.230242
                    multiracial                    0          0.000000
                    white_only            1627772854          0.701129
      45-54     1   american_indian_only           0          0.000000
                    asian_only              46899489          1.000000
                    black_only             585450683          0.512980
                    multiracial             31738302          1.000000
                    white_only            1426236563          0.762352
                2   american_indian_only    25767498          1.000000
                    asian_only              82412760          1.000000
                    black_only             642223949          0.382385
                    multiracial             27585638          0.000000
                    white_only            1759141113          0.754317
      55-64     1   american_indian_only           0          0.000000
                    asian_only                     0          0.000000
                    black_only             667014493          0.375883
                    multiracial             22860013          0.000000
                    white_only            2032680156          0.702025
                2   american_indian_only    27139014          0.000000
                    asian_only                     0          0.000000
                    black_only             850851569          0.404279
                    multiracial                    0          0.000000
                    white_only            1704576671          0.687346

                                          marital_status_2  marital_status_3  \
state age_group sex race_grouped
1     18-24     1   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.000000          0.000000
                    multiracial                   0.000000          0.000000
                    white_only                    0.000000          0.000000
                2   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.000000          0.000000
                    multiracial                   0.000000          0.000000
                    white_only                    0.000000          0.000000
      25-34     1   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.000000          0.000000
                    multiracial                   0.000000          0.000000
                    white_only                    0.000000          0.000000
                2   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.000000          0.000000
                    multiracial                   0.000000          0.000000
                    white_only                    0.000000          0.000000
      35-44     1   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.000000          0.000000
                    multiracial                   0.000000          0.000000
                    white_only                    0.000000          0.000000
                2   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.000000          0.000000
                    multiracial                   0.000000          0.000000
                    white_only                    0.015620          0.000000
      45-54     1   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.000000          0.000000
                    multiracial                   0.000000          0.000000
                    white_only                    0.017482          0.029802
                2   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.000000          0.062167
                    multiracial                   0.000000          1.000000
                    white_only                    0.010575          0.048757
      55-64     1   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.000000          0.143212
                    multiracial                   0.000000          0.000000
                    white_only                    0.022032          0.043310
                2   american_indian_only          0.000000          1.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.000000          0.075011
                    multiracial                   0.000000          0.000000
                    white_only                    0.000000          0.056590

                                          marital_status_4  marital_status_5  \
state age_group sex race_grouped
1     18-24     1   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.000000          0.000000
                    multiracial                   0.000000          0.000000
                    white_only                    0.000000          0.000000
                2   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.000000          0.000000
                    multiracial                   0.000000          0.000000
                    white_only                    0.000000          0.000000
      25-34     1   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.000000          0.000000
                    multiracial                   0.000000          0.000000
                    white_only                    0.015307          0.028733
                2   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.037291          0.037169
                    multiracial                   0.000000          0.000000
                    white_only                    0.038874          0.000000
      35-44     1   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.086046          0.000000
                    multiracial                   0.000000          0.000000
                    white_only                    0.127589          0.016546
                2   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.152063          0.000000
                    multiracial                   0.000000          0.000000
                    white_only                    0.092881          0.027059
      45-54     1   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.225212          0.066295
                    multiracial                   0.000000          0.000000
                    white_only                    0.093458          0.015736
                2   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.198202          0.000000
                    multiracial                   0.000000          0.000000
                    white_only                    0.152311          0.000000
      55-64     1   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.263363          0.000000
                    multiracial                   0.000000          0.000000
                    white_only                    0.116621          0.009507
                2   american_indian_only          0.000000          0.000000
                    asian_only                    0.000000          0.000000
                    black_only                    0.121501          0.127872
                    multiracial                   0.000000          0.000000
                    white_only                    0.159022          0.012649

                                          marital_status_6  \
state age_group sex race_grouped
1     18-24     1   american_indian_only          0.000000
                    asian_only                    0.000000
                    black_only                    1.000000
                    multiracial                   0.000000
                    white_only                    0.910124
                2   american_indian_only          0.000000
                    asian_only                    1.000000
                    black_only                    1.000000
                    multiracial                   1.000000
                    white_only                    0.866174
      25-34     1   american_indian_only          0.000000
                    asian_only                    0.000000
                    black_only                    0.765398
                    multiracial                   0.000000
                    white_only                    0.455212
                2   american_indian_only          0.000000
                    asian_only                    0.000000
                    black_only                    0.831329
                    multiracial                   0.000000
                    white_only                    0.302903
      35-44     1   american_indian_only          0.000000
                    asian_only                    0.000000
                    black_only                    0.587937
                    multiracial                   0.000000
                    white_only                    0.118741
                2   american_indian_only          0.000000
                    asian_only                    0.000000
                    black_only                    0.617695
                    multiracial                   0.000000
                    white_only                    0.163312
      45-54     1   american_indian_only          0.000000
                    asian_only                    0.000000
                    black_only                    0.195512
                    multiracial                   0.000000
                    white_only                    0.081169
                2   american_indian_only          0.000000
                    asian_only                    0.000000
                    black_only                    0.357247
                    multiracial                   0.000000
                    white_only                    0.034039
      55-64     1   american_indian_only          0.000000
                    asian_only                    0.000000
                    black_only                    0.217542
                    multiracial                   1.000000
                    white_only                    0.106507
                2   american_indian_only          0.000000
                    asian_only                    0.000000
                    black_only                    0.271337
                    multiracial                   0.000000
                    white_only                    0.084393

                                          hispanic_flag_Hispanic  \
state age_group sex race_grouped
1     18-24     1   american_indian_only                0.000000
                    asian_only                          0.000000
                    black_only                          0.000000
                    multiracial                         0.000000
                    white_only                          0.040093
                2   american_indian_only                0.000000
                    asian_only                          0.000000
                    black_only                          0.000000
                    multiracial                         0.000000
                    white_only                          0.083225
      25-34     1   american_indian_only                0.000000
                    asian_only                          0.000000
                    black_only                          0.000000
                    multiracial                         0.000000
                    white_only                          0.035041
                2   american_indian_only                0.000000
                    asian_only                          0.000000
                    black_only                          0.000000
                    multiracial                         0.000000
                    white_only                          0.048650
      35-44     1   american_indian_only                0.000000
                    asian_only                          0.000000
                    black_only                          0.000000
                    multiracial                         0.000000
                    white_only                          0.065269
                2   american_indian_only                0.000000
                    asian_only                          0.000000
                    black_only                          0.000000
                    multiracial                         0.000000
                    white_only                          0.084151
      45-54     1   american_indian_only                0.000000
                    asian_only                          0.000000
                    black_only                          0.000000
                    multiracial                         0.000000
                    white_only                          0.000000
                2   american_indian_only                0.000000
                    asian_only                          0.000000
                    black_only                          0.000000
                    multiracial                         0.000000
                    white_only                          0.028147
      55-64     1   american_indian_only                0.000000
                    asian_only                          0.000000
                    black_only                          0.000000
                    multiracial                         0.000000
                    white_only                          0.039703
                2   american_indian_only                0.000000
                    asian_only                          0.000000
                    black_only                          0.000000
                    multiracial                         0.000000
                    white_only                          0.026379

                                          hispanic_flag_Non-Hispanic  \
state age_group sex race_grouped
1     18-24     1   american_indian_only                    0.000000
                    asian_only                              0.000000
                    black_only                              1.000000
                    multiracial                             0.000000
                    white_only                              0.959907
                2   american_indian_only                    0.000000
                    asian_only                              1.000000
                    black_only                              1.000000
                    multiracial                             1.000000
                    white_only                              0.916775
      25-34     1   american_indian_only                    1.000000
                    asian_only                              1.000000
                    black_only                              1.000000
                    multiracial                             0.000000
                    white_only                              0.964959
                2   american_indian_only                    1.000000
                    asian_only                              1.000000
                    black_only                              1.000000
                    multiracial                             1.000000
                    white_only                              0.951350
      35-44     1   american_indian_only                    0.000000
                    asian_only                              1.000000
                    black_only                              1.000000
                    multiracial                             0.000000
                    white_only                              0.934731
                2   american_indian_only                    0.000000
                    asian_only                              1.000000

In [431]:
grouped.shape

(3060, 24)

In [432]:
grouped.columns

Index(['weight', 'marital_status_1', 'marital_status_2', 'marital_status_3',
       'marital_status_4', 'marital_status_5', 'marital_status_6',
       'hispanic_flag_Hispanic', 'hispanic_flag_Non-Hispanic',
       'education_grouped_associates', 'education_grouped_bachelors',
       'education_grouped_high_school_completed',
       'education_grouped_less_than_highschool',
       'education_grouped_masters_and_above',
       'family_income_grouped_high_income', 'family_income_grouped_low_income',
       'family_income_grouped_lower_middle_class',
       'family_income_grouped_middle_class',
       'family_income_grouped_upper_middle_class',
       'children_grouped_1-2 children', 'children_grouped_3+ children',
       'children_grouped_No children', 'veteran_1', 'veteran_2'],
      dtype='object')

In [ ]:
grouped_nozeros = grouped[grouped["weight"] > 0] # drop rows with 0 weight
grouped_nozeros

feature_cols = [c for c in grouped_nozeros.columns if c != "weight"]

grouped_nozeros[feature_cols] = grouped_nozeros[feature_cols].div(grouped_nozeros["weight"], axis=0)

grouped_nozeros.head(50)

# 200 rows x 20 years ~ 4000 rows 

# we dropped the zero weight rows so this may vary from year to year

/var/folders/yz/btvl331d4g54624wdzgx_2hc0000gn/T/ipykernel_21423/2293731417.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grouped_nozeros[feature_cols] = grouped_nozeros[feature_cols].div(grouped_nozeros["weight"], axis=0)

                                              weight  marital_status_1  \
state age_group sex race_grouped
1     18-24     1   black_only             338638266      0.000000e+00
                    white_only            1228359227      7.316764e-11
                2   asian_only              25780867      0.000000e+00
                    black_only             321128931      0.000000e+00
                    multiracial             29127629      0.000000e+00
                    white_only             962224315      1.390801e-10
      25-34     1   american_indian_only    38573846      2.592430e-08
                    asian_only              47942734      2.085822e-08
                    black_only             734906886      3.192274e-10
                    white_only            1619786948      3.091442e-10
                2   american_indian_only    48199208      2.074723e-08
                    asian_only              72297085      1.383182e-08
                    black_only             968682631      9.725686e-11
                    multiracial             36235191      2.759748e-08
                    white_only            1556242328      4.229560e-10
      35-44     1   asian_only              25738916      3.885168e-08
                    black_only             509334030      6.400841e-10
                    white_only            1576168845      4.676682e-10
                2   asian_only              48131421      2.077645e-08
                    black_only             657558482      3.501462e-10
                    white_only            1627772854      4.307288e-10
      45-54     1   asian_only              46899489      2.132219e-08
                    black_only             585450683      8.762147e-10
                    multiracial             31738302      3.150767e-08
                    white_only            1426236563      5.345202e-10
                2   american_indian_only    25767498      3.880858e-08
                    asian_only              82412760      1.213404e-08
                    black_only             642223949      5.954071e-10
                    multiracial             27585638      0.000000e+00
                    white_only            1759141113      4.287983e-10
      55-64     1   black_only             667014493      5.635308e-10
                    multiracial             22860013      0.000000e+00
                    white_only            2032680156      3.453690e-10
                2   american_indian_only    27139014      0.000000e+00
                    black_only             850851569      4.751463e-10
                    white_only            1704576671      4.032355e-10
      65+       1   american_indian_only    34028519      0.000000e+00
                    asian_only              18936690      5.280754e-08
                    black_only             492201471      1.223568e-09
                    multiracial             22713010      4.402763e-08
                    white_only            2715925543      2.726845e-10
                2   american_indian_only    23383341      0.000000e+00
                    black_only             917656498      1.658790e-10
                    multiracial             39164838      0.000000e+00
                    white_only            3228062548      1.659593e-10
2     18-24     1   american_indian_only    58646740      0.000000e+00
                    asian_only               9977498      0.000000e+00
                    black_only               5640824      0.000000e+00
                    multiracial              9671812      0.000000e+00
                    white_only             123205686      9.849913e-10

                                          marital_status_2  marital_status_3  \
state age_group sex race_grouped
1     18-24     1   black_only                0.000000e+00      0.000000e+00
                    white_only                0.000000e+00      0.000000e+00
                2   asian_only                0.000000e+00      0.000000e+00
                    black_only                0.000000e+00      0.000000e+00
                    multiracial               0.000000e+00      0.000000e+00
                    white_only                0.000000e+00      0.000000e+00
      25-34     1   american_indian_only      0.000000e+00      0.000000e+00
                    asian_only                0.000000e+00      0.000000e+00
                    black_only                0.000000e+00      0.000000e+00
                    white_only                0.000000e+00      0.000000e+00
                2   american_indian_only      0.000000e+00      0.000000e+00
                    asian_only                0.000000e+00      0.000000e+00
                    black_only                0.000000e+00      0.000000e+00
                    multiracial               0.000000e+00      0.000000e+00
                    white_only                0.000000e+00      0.000000e+00
      35-44     1   asian_only                0.000000e+00      0.000000e+00
                    black_only                0.000000e+00      0.000000e+00
                    white_only                0.000000e+00      0.000000e+00
                2   asian_only                0.000000e+00      0.000000e+00
                    black_only                0.000000e+00      0.000000e+00
                    white_only                9.595711e-12      0.000000e+00
      45-54     1   asian_only                0.000000e+00      0.000000e+00
                    black_only                0.000000e+00      0.000000e+00
                    multiracial               0.000000e+00      0.000000e+00
                    white_only                1.225778e-11      2.089561e-11
                2   american_indian_only      0.000000e+00      0.000000e+00
                    asian_only                0.000000e+00      0.000000e+00
                    black_only                0.000000e+00      9.679949e-11
                    multiracial               0.000000e+00      3.625075e-08
                    white_only                6.011552e-12      2.771659e-11
      55-64     1   black_only                0.000000e+00      2.147057e-10
                    multiracial               0.000000e+00      0.000000e+00
                    white_only                1.083884e-11      2.130662e-11
                2   american_indian_only      0.000000e+00      3.684732e-08
                    black_only                0.000000e+00      8.815976e-11
                    white_only                0.000000e+00      3.319906e-11
      65+       1   american_indian_only      0.000000e+00      2.938711e-08
                    asian_only                0.000000e+00      0.000000e+00
                    black_only                0.000000e+00      2.840905e-10
                    multiracial               0.000000e+00      0.000000e+00
                    white_only                5.565302e-12      4.883431e-11
                2   american_indian_only      0.000000e+00      0.000000e+00
                    black_only                3.571543e-11      3.793632e-10
                    multiracial               0.000000e+00      0.000000e+00
                    white_only                3.681619e-12      9.395868e-11
2     18-24     1   american_indian_only      0.000000e+00      0.000000e+00
                    asian_only                0.000000e+00      0.000000e+00
                    black_only                0.000000e+00      0.000000e+00
                    multiracial               0.000000e+00      0.000000e+00
                    white_only                0.000000e+00      0.000000e+00

                                          marital_status_4  marital_status_5  \
state age_group sex race_grouped
1     18-24     1   black_only                0.000000e+00      0.000000e+00
                    white_only                0.000000e+00      0.000000e+00
                2   asian_only                0.000000e+00      0.000000e+00
                    black_only                0.000000e+00      0.000000e+00
                    multiracial               0.000000e+00      0.000000e+00
                    white_only                0.000000e+00      0.000000e+00
      25-34     1   american_indian_only      0.000000e+00      0.000000e+00
                    asian_only                0.000000e+00      0.000000e+00
                    black_only                0.000000e+00      0.000000e+00
                    white_only                9.450027e-12      1.773871e-11
                2   american_indian_only      0.000000e+00      0.000000e+00
                    asian_only                0.000000e+00      0.000000e+00
                    black_only                3.849670e-11      3.837097e-11
                    multiracial               0.000000e+00      0.000000e+00
                    white_only                2.497972e-11      0.000000e+00
      35-44     1   asian_only                0.000000e+00      0.000000e+00
                    black_only                1.689384e-10      0.000000e+00
                    white_only                8.094874e-11      1.049782e-11
                2   asian_only                0.000000e+00      0.000000e+00
                    black_only                2.312546e-10      0.000000e+00
                    white_only                5.705987e-11      1.662322e-11
      45-54     1   asian_only                0.000000e+00      0.000000e+00
                    black_only                3.846813e-10      1.132384e-10
                    multiracial               0.000000e+00      0.000000e+00
                    white_only                6.552763e-11      1.103323e-11
                2   american_indian_only      0.000000e+00      0.000000e+00
                    asian_only                0.000000e+00      0.000000e+00
                    black_only                3.086174e-10      0.000000e+00
                    multiracial               0.000000e+00      0.000000e+00
                    white_only                8.658272e-11      0.000000e+00
      55-64     1   black_only                3.948385e-10      0.000000e+00
                    multiracial               0.000000e+00      0.000000e+00
                    white_only                5.737285e-11      4.676876e-12
                2   american_indian_only      0.000000e+00      0.000000e+00
                    black_only                1.427995e-10      1.502870e-10
                    white_only                9.329111e-11      7.420853e-12
      65+       1   american_indian_only      0.000000e+00      0.000000e+00
                    asian_only                0.000000e+00      0.000000e+00
                    black_only                5.240297e-10      0.000000e+00
                    multiracial               0.000000e+00      0.000000e+00
                    white_only                3.028633e-11      0.000000e+00
                2   american_indian_only      4.276549e-08      0.000000e+00
                    black_only                2.043802e-10      3.219009e-11
                    multiracial               2.553311e-08      0.000000e+00
                    white_only                4.268565e-11      0.000000e+00
2     18-24     1   american_indian_only      2.346967e-09      0.000000e+00
                    asian_only                0.000000e+00      0.000000e+00
                    black_only                0.000000e+00      0.000000e+00
                    multiracial               0.000000e+00      0.000000e+00
                    white_only                3.275840e-10      0.000000e+00

                                          marital_status_6  \
state age_group sex race_grouped
1     18-24     1   black_only                2.953004e-09
                    white_only                7.409265e-10
                2   asian_only                3.878846e-08
                    black_only                3.114014e-09
                    multiracial               3.433166e-08
                    white_only                9.001786e-10
      25-34     1   american_indian_only      0.000000e+00
                    asian_only                0.000000e+00
                    black_only                1.041489e-09
                    white_only                2.810322e-10
                2   american_indian_only      0.000000e+00
                    asian_only                0.000000e+00
                    black_only                8.582053e-10
                    multiracial               0.000000e+00
                    white_only                1.946377e-10
      35-44     1   asian_only                0.000000e+00
                    black_only                1.154326e-09
                    white_only                7.533504e-11
                2   asian_only                0.000000e+00
                    black_only                9.393765e-10
                    white_only                1.003288e-10
      45-54     1   asian_only                0.000000e+00
                    black_only                3.339515e-10
                    multiracial               0.000000e+00
                    white_only                5.691152e-11
                2   american_indian_only      0.000000e+00
                    asian_only                0.000000e+00
                    black_only                5.562652e-10
                    multiracial               0.000000e+00
                    white_only                1.935004e-11
      55-64     1   black_only                3.261428e-10
                    multiracial               4.374451e-08
                    white_only                5.239713e-11
                2   american_indian_only      0.000000e+00
                    black_only                3.189006e-10
                    white_only                4.950942e-11
      65+       1   american_indian_only      0.000000e+00
                    asian_only                0.000000e+00
                    black_only                0.000000e+00
                    multiracial               0.000000e+00
                    white_only                1.082813e-11
                2   american_indian_only      0.000000e+00
                    black_only                2.722045e-10
                    multiracial               0.000000e+00
                    white_only                3.498115e-12
2     18-24     1   american_indian_only      1.470428e-08
                    asian_only                1.002255e-07
                    black_only                1.772791e-07
                    multiracial               1.033932e-07
                    white_only                6.803933e-09

                                          hispanic_flag_Hispanic  \
state age_group sex race_grouped
1     18-24     1   black_only                      0.000000e+00
                    white_only                      3.263980e-11
                2   asian_only                      0.000000e+00
                    black_only                      0.000000e+00
                    multiracial                     0.000000e+00
                    white_only                      8.649229e-11
      25-34     1   american_indian_only            0.000000e+00
                    asian_only                      0.000000e+00
                    black_only                      0.000000e+00
                    white_only                      2.163310e-11
                2   american_indian_only            0.000000e+00
                    asian_only                      0.000000e+00
                    black_only                      0.000000e+00
                    multiracial                     0.000000e+00
                    white_only                      3.126104e-11
      35-44     1   asian_only                      0.000000e+00
                    black_only                      0.000000e+00
                    white_only                      4.141000e-11
                2   asian_only                      0.000000e+00
                    black_only                      0.000000e+00
                    white_only                      5.169705e-11
      45-54     1   asian_only                      0.000000e+00
                    black_only                      0.000000e+00
                    multiracial                     0.000000e+00
                    white_only                      0.000000e+00
                2   american_indian_only            0.000000e+00
                    asian_only                      0.000000e+00
                    black_only                      0.000000e+00
                    multiracial                     0.000000e+00
                    white_only                      1.600053e-11
      55-64     1   black_only                      0.000000e+00
                    multiracial                     0.000000e+00
                    white_only                      1.953238e-11
                2   american_indian_only            0.000000e+00
                    black_only                      0.000000e+00
                    white_only                      1.547561e-11
      65+       1   american_indian_only            0.000000e+00
                    asian_only                      0.000000e+00
                    black_only                      0.000000e+00
                    multiracial                     0.000000e+00
                    white_only                      0.000000e+00
                2   american_indian_only            4.276549e-08
                    black_only                      0.000000e+00
                    multiracial                     0.000000e+00
                    white_only                      4.330260e-12
2     18-24     1   american_indian_only            0.000000e+00
                    asian_only                      0.000000e+00
                    black_only                      1.772791e-07
                    multiracial                     0.000000e+00
                    white_only                      3.275840e-10

                                          hispanic_flag_Non-Hispanic  \
state age_group sex race_grouped
1     18-24     1   black_only                          2.953004e-09
                    white_only                          7.814543e-10
                2   asian_only                          3.878846e-08
                    black_only                          3.114014e-09
                    multiracial                         3.433166e-08
                    white_only                          9.527664e-10
      25-34     1   american_indian_only                2.592430e-08
                    asian_only                          2.085822e-08
                    black_only                          1.360717e-09
                    white_only                          5.957320e-10
                2   american_indian_only                2.074723e-08
                    asian_only                          1.383182e-08
                    black_only                          1.032330e-09
                    multiracial                         2.759748e-08
                    white_only                          6.113124e-10
      35-44     1   asian_only                          3.885168e-08
                    black_only                          1.963348e-09
                    white_only                          5.930398e-10
                2   asian_only                          2.077645e-08
                    black_only                          1.520777e-09
                    white_only                          5.626393e-10
      45-54     1   asian_only                          2.132219e-08
                    black_only                          1.708086e-09
                    multiracial                         3.150767e-08
                    white_only                          7.011460e-10
                2   american_indian_only                3.880858e-08
                    asian_only                          1.213404e-08